language: php
php:
  - 5.5
  - 5.6
  - 7.0
# whitelist
branches:
  only:
    - master
    - develop
before_script:
  - composer install
  - echo 'error_reporting = E_ALL & ~E_STRICT' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: phpunit --configuration tests/phpunit.xml --coverage-text